"""
Milestone 5 — Grounded answer generation via Groq LLM.

Usage:
  python3 generate.py                 # run the 5 evaluation queries
  python3 generate.py "your question" # ad-hoc query

Importable by app.py:

    from generate import ask
    result = ask("Which professor is best for CSCI 135?")
    print(result["answer"])
    print(result["sources"])
"""

import os
import sys

from dotenv import load_dotenv
from groq import Groq

from retrieve import get_retriever

load_dotenv()

GROQ_MODEL = "llama-3.3-70b-versatile"
TOP_K = 6

SYSTEM_PROMPT = """\
You are a student advisor assistant for Hunter College Computer Science courses. \
You answer questions ONLY using the provided document excerpts.

STRICT RULES:
1. Answer ONLY from the provided context. Do not use any outside knowledge.
2. If the context does not contain enough information to answer the question, \
respond with exactly: "I don't have enough information in my sources to answer that question."
3. Do not guess, infer, or supplement with general knowledge.
4. Be specific and reference which professor or document your answer comes from.\
"""

_client = None
_retrieve = None


def _get_client():
    global _client
    if _client is None:
        _client = Groq(api_key=os.environ["GROQ_API_KEY"])
    return _client


def _get_retrieve():
    global _retrieve
    if _retrieve is None:
        _retrieve = get_retriever(top_k=TOP_K)
    return _retrieve


def ask(query: str, top_k: int = TOP_K) -> dict:
    """Return {"answer": str, "sources": list[str]} for the given query.

    Sources are extracted programmatically from chunk metadata — never
    generated by the LLM — so attribution is always grounded.
    """
    retrieve = _get_retrieve()
    chunks = retrieve(query, k=top_k)

    # Build numbered context block
    context_lines = []
    for i, chunk in enumerate(chunks, 1):
        meta = chunk["metadata"]
        context_lines.append(
            f"[{i}] Source: {meta.get('source')} | Professor: {meta.get('professor')}\n"
            f"{chunk['text']}"
        )
    context_block = "\n\n".join(context_lines)

    user_message = (
        f"Context excerpts:\n\n{context_block}\n\n"
        f"Question: {query}"
    )

    response = _get_client().chat.completions.create(
        model=GROQ_MODEL,
        temperature=0.1,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": user_message},
        ],
    )
    answer = response.choices[0].message.content.strip()

    # Programmatic source attribution — deduplicated, in retrieval order
    seen = set()
    sources = []
    for chunk in chunks:
        src = chunk["metadata"].get("source", "unknown")
        if src not in seen:
            seen.add(src)
            sources.append(src)

    return {"answer": answer, "sources": sources}


# ---------------------------------------------------------------------------
# CLI / evaluation harness
# ---------------------------------------------------------------------------

EVAL_QUERIES = [
    "What do students say about the clarity of Professor Tong Yi's lectures in CSCI 13500?",
    "How much time per week does CSCI 13500 (Software Analysis & Design 1) require?",
    "How responsive is Professor Mahdi Makki to student questions?",
    "What do students say about the clarity of Professor Susan Epstein's grading rubrics?",
    "Does Professor Mahdi Makki's course connect to real-world / industry CS work?",
]

OUT_OF_SCOPE_QUERIES = [
    "What is the capital of France?",
    "Who invented the internet?",
]


def main():
    queries = EVAL_QUERIES + OUT_OF_SCOPE_QUERIES
    if len(sys.argv) > 1:
        queries = [" ".join(sys.argv[1:])]

    for i, query in enumerate(queries, 1):
        print("\n" + "=" * 72)
        print(f"QUERY {i}: {query}")
        print("=" * 72)
        result = ask(query)
        print(f"\nANSWER:\n{result['answer']}")
        print(f"\nSOURCES: {', '.join(result['sources'])}")


if __name__ == "__main__":
    main()
